import {configured,observe,signIn,signOut,action} from './firebase.js';
import {stats} from './service.js';
import {escape as e} from './ui.js';
import {home} from './home.js';
import * as views from './views.js';
import {mountEffects} from './effects.js';
const main=document.querySelector('#main'),errorBox=document.querySelector('#error'),notice=document.querySelector('#notice');
let state={user:null,profile:null,admin:false,loading:true,dataLoading:true,listings:[],organizations:[],ngoReservations:[],hostelReservations:[],requests:[],reports:[]},cleanup=()=>{},dirty=false,busy=false,privateInfo={},privateId='',privateLoading=false,backendError='';
function error(err){const map={'auth/popup-closed-by-user':'Google sign-in was cancelled. You can try again.','auth/popup-blocked':'Allow the Google sign-in popup in your browser, then try again.','auth/unauthorized-domain':'This website domain must be authorized in Firebase Authentication.','auth/operation-not-allowed':'Google sign-in must be enabled in Firebase Authentication.','functions/not-found':'The Firebase backend has not been deployed yet.','functions/internal':'The Firebase backend could not complete this request. Please try again.'};errorBox.textContent=map[err.code]||err.message||String(err);errorBox.hidden=false;errorBox.className='error';errorBox.focus({preventScroll:true});}
function menu(open){document.querySelector('#main-navigation').classList.toggle('open',open);document.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));}
function nav(){const a=document.querySelector('.nav-login');a.textContent=state.user?'My account':'Sign in';document.querySelectorAll('#main-navigation a').forEach(a=>{const u=new URL(a.href),active=u.pathname===location.pathname&&!u.hash;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.querySelector('#admin-link')?.remove();if(state.admin)document.querySelector('#main-navigation').insertAdjacentHTML('beforeend','<a href="/admin" id="admin-link" data-link>Admin</a>');}
async function navigate(url){const target=new URL(url,location.origin);if(target.origin!==location.origin)return;const same=target.pathname===location.pathname;history.pushState({},'',target);errorBox.hidden=true;menu(false);dirty=false;privateInfo={};privateId='';if(!same){render();window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}if(target.hash)requestAnimationFrame(()=>document.getElementById(target.hash.slice(1))?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));nav();}
function render(){cleanup();cleanup=()=>{};menu(false);const p=location.pathname;try{if(p==='/')main.innerHTML=home(state.listings.filter(l=>stats(state,l).available>0).slice(0,3).map(l=>views.card(state,l)).join(''));else if(p==='/login')main.innerHTML=views.login(state);else if(p==='/explore')main.innerHTML=views.explore(state);else if(p==='/organizations')main.innerHTML=views.organizations(state);else if(p==='/dashboard')main.innerHTML=state.admin&&!state.profile?views.admin(state):views.dashboard(state);else if(p==='/admin')main.innerHTML=views.admin(state);else if(p==='/listings/new')main.innerHTML=views.listingForm(state);else if(/^\/listings\/[^/]+\/edit$/.test(p)){
 const id=p.split('/')[2];
 if(state.profile?.role==='hostel'&&privateId!==id){main.innerHTML='<div class="page"><h1>Loading pickup details…</h1></div>';if(!privateLoading){privateLoading=true;action('privateListing',{id}).then(info=>{privateInfo=info;privateId=id;if(location.pathname===p)render();}).catch(error).finally(()=>privateLoading=false);}}
 else main.innerHTML=views.listingForm(state,id,privateInfo);
 }else if(/^\/food\/[^/]+$/.test(p))main.innerHTML=views.listingDetails(state,p.split('/')[2]);else main.innerHTML=views.missing();nav();if(p==='/'){cleanup=mountEffects(main);}if(p==='/explore')filter();if(backendError){notice.textContent=backendError;notice.className='connection-notice';}}catch(err){error(err);}}
function filter(){const f=document.querySelector('#filters');if(!f)return;const values=new FormData(f),q=String(values.get('query')||'').toLowerCase(),list=state.listings.filter(l=>(values.has('unavailable')||stats(state,l).available>0)&&(!values.get('type')||l.type===values.get('type'))&&stats(state,l).available>=Number(values.get('minimum')||0)&&(!values.get('hours')||l.deadline<=Date.now()+Number(values.get('hours'))*3600000)&&`${l.name} ${l.hostel} ${l.area}`.toLowerCase().includes(q));document.querySelector('#results-count').textContent=state.dataLoading?'Loading availability…':`${list.length} listings · All deadlines IST`;document.querySelector('#food-results').innerHTML=list.length?`<div class="food-grid">${list.map(l=>views.card(state,l)).join('')}</div>`:`<div class="empty"><h2>${state.dataLoading?'Checking food availability…':backendError?'Availability is temporarily unavailable.':'No available food right now.'}</h2><p>${state.dataLoading?'Connecting to the food listings.':backendError?'Please try again after the connection is restored.':'Approved hostel kitchens will appear here when they publish surplus meals. Try changing your filters.'}</p></div>`;}
async function run(button,fn){if(busy)return;busy=true;button.disabled=true;errorBox.hidden=true;try{await fn();}catch(err){error(err);}finally{busy=false;if(button.isConnected)button.disabled=false;}}
document.querySelector('#menu-toggle').addEventListener('click',()=>menu(document.querySelector('#menu-toggle').getAttribute('aria-expanded')!=='true'));
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&document.querySelector('#main-navigation').classList.contains('open')){menu(false);document.querySelector('#menu-toggle').focus();}});
document.addEventListener('click',ev=>{const a=ev.target.closest('a[data-link]');if(a&&!ev.ctrlKey&&!ev.metaKey&&!ev.shiftKey&&ev.button===0){ev.preventDefault();navigate(a.href);return;}const b=ev.target.closest('[data-action]');if(!b)return;const name=b.dataset.action,id=b.dataset.id;
 if(name==='cancel-start'){b.parentElement.insertAdjacentHTML('beforeend',`<div class="notice"><p>Cancel this reservation? Boxes return to availability only while the listing is open and before its deadline.</p><button class="button small" data-action="cancel" data-id="${e(id)}">Confirm cancellation</button><button class="text-button" data-action="refresh">Keep reservation</button></div>`);b.disabled=true;return;}
 if(name==='refresh'){dirty=false;notice.textContent='';render();return;}
 
 run(b,async()=>{if(name==='google'){await signIn();dirty=false;render();return;}if(name==='logout'){await signOut();navigate('/login');return;}if(name==='code'){const result=await action('pickupCode',{id});b.outerHTML=`<div class="code">Share at collection<strong>${e(result.code)}</strong></div>`;return;}if(['close','cancel'].includes(name)){const result=await action(name,{id});if(result.error)throw Error(result.error);dirty=false;render();}});
});
document.addEventListener('input',ev=>{if(ev.target.form?.id==='filters'){filter();return;}if(ev.target.closest('form'))dirty=true;});
document.addEventListener('change',ev=>{if(ev.target.form?.id==='filters'){filter();return;}if(ev.target.name==='role'&&ev.target.form?.dataset.form==='onboard'){const hostel=ev.target.value==='hostel';const h=document.querySelector('#hostel-registration'),n=document.querySelector('#ngo-registration');if(h&&n){h.hidden=!hostel;n.hidden=hostel;for(const el of h.querySelectorAll('[name]'))el.required=hostel&&['hostelId','contact','evidence'].includes(el.name);for(const el of n.querySelectorAll('[name]'))el.required=!hostel&&['name','registrationNumber','website','serviceArea','contact','evidence'].includes(el.name);}}if(ev.target.name==='hostelId'){const o=ev.target.selectedOptions[0],f=ev.target.form;if(o&&f){f.elements.name.value=o.dataset.name||'';f.elements.hostelGender.value=o.dataset.gender||'';}}});
document.addEventListener('submit',ev=>{const form=ev.target;if(!form.matches('[data-form]'))return;ev.preventDefault();if(form.dataset.form==='filters'){filter();return;}const b=form.querySelector('button'),data=Object.fromEntries(new FormData(form)),name=form.dataset.form;delete data.authorization;form.dataset.requestId||=crypto.randomUUID();data.requestId=form.dataset.requestId;data.id=form.dataset.id;
 for(const k of ['quantity','total','portions'])if(k in data)data[k]=Number(data[k]);for(const k of ['eta','prepared','deadline'])if(k in data)data[k]=new Date(data[k]).getTime();if(name==='resolveReport')data.close=data.close==='on';
 run(b,async()=>{const result=await action(name,data);if(result.error)throw Error(result.error);dirty=false;if(name==='report'){form.innerHTML='<p role="status">Your concern has been sent to the administrator.</p>';return;}notice.textContent=name==='reserve'?'Reservation saved. Your pickup details will appear in the dashboard.':'Saved successfully.';await navigate(name==='review'||name==='resolveReport'?'/admin':'/dashboard');render();});
});
addEventListener('popstate',()=>{dirty=false;privateInfo={};render();});
setInterval(()=>{if(location.pathname==='/explore')filter();},15000);
render();
setTimeout(()=>{if(state.dataLoading){state.dataLoading=false;backendError='Food availability could not be loaded. Firebase setup may still be pending.';if(!dirty)render();}},15000);
if(configured)observe(patch=>{Object.assign(state,patch);if(patch.dataLoading===false){backendError='';notice.className='';notice.textContent='';}if('user' in patch)dirty=false;if(dirty||busy){nav();return;}render();},err=>{state.dataLoading=false;backendError=err.code==='permission-denied'?'Food data is unavailable. The Firebase access rules need to be deployed.':'Connection to MealBridge is unavailable. Please try again shortly.';if(!dirty)render();}).catch(err=>{state.loading=false;state.dataLoading=false;backendError='MealBridge could not connect to Firebase. Check your connection and reload.';render();error(err);});else{state.loading=false;state.dataLoading=false;backendError='Firebase has not been connected yet.';render();}
