import {chapters,fallback} from './home.js';
export function mountEffects(root){
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let disposed=false,controllers=[],scrollFrame=0,particleFrame=0;const journey=root.querySelector('.journey');let current=-1,progress=0;
 const targets=[...root.querySelectorAll('[data-scene]')];const scenes=new Map();
 async function loadScene(el){if(disposed||reduced.matches||scenes.has(el))return;scenes.set(el,null);try{const {createScene}=await import('./scene.js');if(disposed||!el.isConnected||reduced.matches)return;const c=createScene(el,{hero:el.dataset.scene==='hero'});c.setProgress(progress);scenes.set(el,c);controllers.push(c);}catch{el.innerHTML=fallback();}}
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){loadScene(entry.target);observer.unobserve(entry.target);}}),{rootMargin:'250px'});if(!reduced.matches)targets.forEach(el=>observer.observe(el));
 function update(){scrollFrame=0;if(!journey||disposed)return;const rect=journey.getBoundingClientRect();const desktop=innerWidth>800;progress=reduced.matches?0:Math.max(0,Math.min(1,desktop?(90-rect.top)/(journey.offsetHeight-innerHeight+90):(innerHeight-rect.top)/(journey.offsetHeight+innerHeight)));scenes.forEach((c,el)=>{if(el.dataset.scene==='journey')c?.setProgress(progress);});const stage=progress<.23?0:progress<.5?1:progress<.84?2:3;
 if(stage!==current){current=stage;const [a,b,p]=chapters[stage];journey.querySelector('.chapter-index').textContent=`0${stage+1} / 04`;journey.querySelector('.journey-copy h2').innerHTML=`${a}<br><em>${b}</em>`;journey.querySelector('.journey-copy p').textContent=p;journey.querySelector('[data-count=available]').textContent=stage===0?'List':'Listed';journey.querySelector('[data-count=reserved]').textContent=stage===0?'Book':'Reserved';journey.querySelector('[data-count=collected]').textContent=stage===3?'Done':'Collect';journey.querySelectorAll('.journey-track>span').forEach((el,i)=>el.classList.toggle('current',i===stage));}
 const fill=journey.querySelector('.track-fill');fill.style.transform=`scaleX(${progress})`;}
 const requestUpdate=()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(update);};addEventListener('scroll',requestUpdate,{passive:true});addEventListener('resize',requestUpdate);update();
 const mediaChange=()=>{controllers.forEach(c=>c.dispose());controllers=[];scenes.clear();targets.forEach(el=>{el.innerHTML=fallback();if(!reduced.matches)loadScene(el);});update();};reduced.addEventListener('change',mediaChange);
 let ring,dot;const cursorMove=event=>{if(reduced.matches||!matchMedia('(pointer:fine)').matches)return;dot.style.opacity='1';dot.style.transform=`translate(${event.clientX}px,${event.clientY}px)`;ring.style.transform=dot.style.transform;ring.style.opacity=event.target.closest('input,textarea,select')?'0':'1';ring.classList.toggle('over',!!event.target.closest('a,button,canvas'));};
 if(!reduced.matches&&matchMedia('(pointer:fine)').matches){dot=document.createElement('div');ring=document.createElement('div');dot.className='cursor-dot';ring.className='cursor-ring';document.body.append(dot,ring);addEventListener('pointermove',cursorMove,{passive:true});}
 let textPlayed=false;const text=root.querySelector('.particle-text');const particleObserver=new IntersectionObserver(entries=>{if(!entries[0]?.isIntersecting||textPlayed||reduced.matches)return;textPlayed=true;const canvas=text.querySelector('canvas'),ctx=canvas.getContext('2d');canvas.width=800;canvas.height=180;ctx.font='bold 55px sans-serif';ctx.textAlign='center';ctx.fillText('Share food. Spread care.',400,105);const pixels=ctx.getImageData(0,0,800,180).data,points=[];for(let y=0;y<180;y+=6)for(let x=0;x<800;x+=6)if(pixels[(y*800+x)*4+3]>100)points.push({x,y,dx:(Math.random()-.5)*400,dy:(Math.random()-.5)*170});let elapsed=0,last=performance.now();const frame=now=>{if(disposed)return;const dt=now-last;last=now;if(!document.hidden)elapsed+=Math.min(dt,50);const p=Math.min(1,elapsed/1700);ctx.clearRect(0,0,800,180);ctx.fillStyle='#90ad61';points.forEach(d=>{ctx.beginPath();ctx.arc(d.x+d.dx*(1-p)**3,d.y+d.dy*(1-p)**3,1.5,0,7);ctx.fill();});if(p<1)particleFrame=requestAnimationFrame(frame);else canvas.style.opacity='0';};particleFrame=requestAnimationFrame(frame);});if(text)particleObserver.observe(text);
 let intro,timer,introController;try{if(!sessionStorage.getItem('mealbridge-intro')){sessionStorage.setItem('mealbridge-intro','1');intro=document.createElement('div');intro.className='intro';intro.innerHTML=`<div class="intro-art">${fallback()}</div><p role="status">Preparing something meaningful…</p><div class="indeterminate"></div><button class="text-button">Skip Intro</button>`;document.body.append(intro);const close=()=>{introController?.dispose();intro.remove();};intro.querySelector('button').onclick=close;timer=setTimeout(close,reduced.matches?400:1800);if(!reduced.matches)import('./scene.js').then(({createScene})=>{if(intro.isConnected&&!disposed)introController=createScene(intro.querySelector('.intro-art'),{loader:true});}).catch(()=>{});}}catch{}
 return()=>{disposed=true;controllers.forEach(c=>c.dispose());introController?.dispose();clearTimeout(timer);intro?.remove();observer.disconnect();particleObserver.disconnect();cancelAnimationFrame(scrollFrame);cancelAnimationFrame(particleFrame);removeEventListener('scroll',requestUpdate);removeEventListener('resize',requestUpdate);removeEventListener('pointermove',cursorMove);reduced.removeEventListener('change',mediaChange);dot?.remove();ring?.remove();};
}
